### ISSUE TITLE
After Disabling Sections Visibility, Test Cases are loaded

### ISSUE THREAD

**Issue by merlinpratheesh** [gmanojisaac/reorg-testerapp#3]
expectation: Testcase  should not be loaded

**Comment by gmanojisaac** [comment]
Please check in release.
Create candidserenity.com as Member
your own gmail as Demo user.

Create a project and load the test cases from a member
and now change the visibility
the testcases of old selection should not be visible

**Comment by merlinpratheesh** [comment]
Issue Solved in new release
